name: '@cloud-down/eslint-config-vue'

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/

      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git tag "v$(npm view . version)"
          git push --tags
